
title: Feng Li


#sidebar links
email: lifeng16.hf@gmail.com; fengli@hfut.edu.cn
<a href="https://scholar.google.com/citations?user=mYfWM6oAAAAJ&hl=en&oi=ao">Google Scholar</a>
#phone: 012 345 6789
#linkedin: alandoe
github: KingSFU
port: 4001
#Update all the sections by editing the files inside _includes folder.
